spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/switter-db
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.show-sql: true
      hibernate.format_sql: true

logging:
  level:
    org:
      springframework:
        security: debug



