spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/switter-db
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: debug

