spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/switter-db
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
logging:
  level:
    org:
      springframework:
        security: debug



